Parameters:
  ConnectionArn:
    Description: The CodeConnections ARN for your source repository.
    Type: String
  FullRepositoryId:
    Description: The full repository ID to use with your CodeConnections connection.
    Type: String
  BranchName:
    Description: The branch name to use with your CodeConnections connection.
    Type: String
  CodePipelineName:
    Description: The CodePipeline pipeline name that will build your maven source project.
    Type: String
    Default: SimpleScheduleMavenBuildService
  CICodeBuildSpec:
    Description: The CodeBuild project build spec maven configuration
    Type: String
    Default: |
      version: 0.2
      
      phases:
        build:
          commands:
            - echo "Starting maven build"
            - mvn -B package --file pom.xml
            - echo "Completed maven build successfully!"
  ScheduleExpression:
    Description: The amazon event bridge schedule cron expression that would trigger a pipeline periodically. A cron expression consists of five required fields separated by white space (minutes, hours, day-of-month, month, day-of-week, and one optional field, year). The default cron expression would trigger the pipeline at 9AM everyday from Monday to Friday. For scheduling nightly builds you can use (0 0 ? * * *). For scheduling weekly builds you can use (0 0 ? * SUN *)
    Type: String
    Default: '0 9 ? * MON-FRI *'
  ScheduleExpressionTimezone:
    Description: The timezone in which the event bridge scheduling expression is evaluated. For example, America/Los_Angeles | America/New_York | UTC
    Type: String
    Default: 'America/Los_Angeles'
  RetentionPolicy:
    Description: Define if you'd like the resource retained or deleted when the
      CloudFormation stack is deleted.
    Type: String
    Default: Delete
    AllowedValues:
      - Delete
      - Retain
Resources:
  SimpleMavenBuildScheduler:
    Type: AWS::Scheduler::Schedule
    DependsOn:
      - CodePipeline
    Properties:
      Description: "Schedule that would trigger a maven build pipeline periodically"
      Name:
        Fn::Join:
          - '-'
          - - SimpleMavenBuildScheduler
            - Fn::Select:
                - 4
                - Fn::Split:
                    - '-'
                    - Fn::Select:
                        - 2
                        - Fn::Split:
                            - /
                            - Ref: AWS::StackId
      ScheduleExpression: !Sub
        - cron(${scheduleExpression})
        - scheduleExpression: !Ref ScheduleExpression
      FlexibleTimeWindow:
        Mode: "OFF"
      ScheduleExpressionTimezone: !Ref ScheduleExpressionTimezone
      State: "ENABLED"
      Target:
        Arn: !Sub
          - arn:${AWS::Partition}:codepipeline:${AWS::Region}:${AWS::AccountId}:${pipelineName}
          - pipelineName: !Ref CodePipelineName
        RoleArn: !GetAtt EventBridgeMavenSchedulerRole.Arn
  EventBridgeMavenSchedulerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: scheduler.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: AmazonCodePipelineMavenEventBridgeSchedulerPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'codepipeline:StartPipelineExecution'
                Resource: !Sub
                  - arn:${AWS::Partition}:codepipeline:${AWS::Region}:${AWS::AccountId}:${pipelineName}
                  - pipelineName: !Ref CodePipelineName
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
        Version: '2012-10-17'
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Effect: Allow
                Resource:
                  - !Sub
                    - arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${projectName}
                    - projectName:
                        Fn::Join:
                          - '-'
                          - - SimpleScheduleMavenBuildProject
                            - Fn::Select:
                                - 4
                                - Fn::Split:
                                    - '-'
                                    - Fn::Select:
                                        - 2
                                        - Fn::Split:
                                            - /
                                            - Ref: AWS::StackId
                  - !Sub
                    - arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${projectName}:*
                    - projectName:
                        Fn::Join:
                          - '-'
                          - - SimpleScheduleMavenBuildProject
                            - Fn::Select:
                                - 4
                                - Fn::Split:
                                    - '-'
                                    - Fn::Select:
                                        - 2
                                        - Fn::Split:
                                            - /
                                            - Ref: AWS::StackId
              - Action:
                  - codebuild:BatchPutCodeCoverages
                  - codebuild:BatchPutTestCases
                  - codebuild:CreateReport
                  - codebuild:CreateReportGroup
                  - codebuild:UpdateReport
                Effect: Allow
                Resource: !Sub
                  - arn:${AWS::Partition}:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/${projectName}-*
                  - projectName:
                      Fn::Join:
                        - '-'
                        - - SimpleScheduleMavenBuildProject
                          - Fn::Select:
                              - 4
                              - Fn::Split:
                                  - '-'
                                  - Fn::Select:
                                      - 2
                                      - Fn::Split:
                                          - /
                                          - Ref: AWS::StackId
              - Action:
                  - s3:GetBucket*
                  - s3:GetObject*
                  - s3:List*
                Effect: Allow
                Resource:
                  - !GetAtt CodePipelineArtifactsBucket.Arn
                  - !Sub
                    - ${arn}/*
                    - arn: !GetAtt CodePipelineArtifactsBucket.Arn
            Version: '2012-10-17'
          PolicyName: CodeBuildProjectRoleDefaultPolicy
  CodeBuildDefaultPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource:
              - !Join
                - ''
                - - !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/
                  - Fn::Join:
                      - '-'
                      - - SimpleScheduleMavenBuildProject
                        - Fn::Select:
                            - 4
                            - Fn::Split:
                                - '-'
                                - Fn::Select:
                                    - 2
                                    - Fn::Split:
                                        - /
                                        - Ref: AWS::StackId
                  - ':*'
              - !Join
                - ''
                - - !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/
                  - Fn::Join:
                      - '-'
                      - - SimpleScheduleMavenBuildProject
                        - Fn::Select:
                            - 4
                            - Fn::Split:
                                - '-'
                                - Fn::Select:
                                    - 2
                                    - Fn::Split:
                                        - /
                                        - Ref: AWS::StackId
          - Action:
              - codebuild:BatchPutCodeCoverages
              - codebuild:BatchPutTestCases
              - codebuild:CreateReport
              - codebuild:CreateReportGroup
              - codebuild:UpdateReport
            Effect: Allow
            Resource: !Join
              - ''
              - - !Sub arn:${AWS::Partition}:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/
                - Fn::Join:
                    - '-'
                    - - SimpleScheduleMavenBuildProject
                      - Fn::Select:
                          - 4
                          - Fn::Split:
                              - '-'
                              - Fn::Select:
                                  - 2
                                  - Fn::Split:
                                      - /
                                      - Ref: AWS::StackId
                - '-*'
          - Action:
              - s3:GetBucket*
              - s3:GetObject*
              - s3:List*
            Effect: Allow
            Resource:
              - !GetAtt CodePipelineArtifactsBucket.Arn
              - !Join
                - /
                - - !GetAtt CodePipelineArtifactsBucket.Arn
                  - '*'
        Version: '2012-10-17'
      PolicyName: CodeBuildDefaultPolicy
      Roles:
        - !Ref CodeBuildRole
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      Cache:
        Type: NO_CACHE
      Description: Build maven source code
      EncryptionKey: alias/aws/s3
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: false
        Type: LINUX_CONTAINER
      Name:
        Fn::Join:
          - '-'
          - - SimpleScheduleMavenBuildProject
            - Fn::Select:
                - 4
                - Fn::Split:
                    - '-'
                    - Fn::Select:
                        - 2
                        - Fn::Split:
                            - /
                            - Ref: AWS::StackId
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        BuildSpec: !Ref CICodeBuildSpec
        Type: NO_SOURCE
  CodePipelineArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    UpdateReplacePolicy: !Ref RetentionPolicy
    DeletionPolicy: !Ref RetentionPolicy
  CodePipelineArtifactsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CodePipelineArtifactsBucket
      PolicyDocument:
        Statement:
          - Action: s3:*
            Condition:
              Bool:
                aws:SecureTransport: 'false'
            Effect: Deny
            Principal:
              AWS: '*'
            Resource:
              - !GetAtt CodePipelineArtifactsBucket.Arn
              - !Join
                - /
                - - !GetAtt CodePipelineArtifactsBucket.Arn
                  - '*'
        Version: '2012-10-17'
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
        Version: '2012-10-17'
  CodePipelineDefaultPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:Abort*
              - s3:DeleteObject*
              - s3:GetBucket*
              - s3:GetObject*
              - s3:List*
              - s3:PutObject
              - s3:PutObjectLegalHold
              - s3:PutObjectRetention
              - s3:PutObjectTagging
              - s3:PutObjectVersionTagging
            Effect: Allow
            Resource:
              - !GetAtt CodePipelineArtifactsBucket.Arn
              - !Join
                - /
                - - !GetAtt CodePipelineArtifactsBucket.Arn
                  - '*'
          - Action: sts:AssumeRole
            Effect: Allow
            Resource:
              - !GetAtt CodeBuildActionRole.Arn
              - !GetAtt CodeConnectionsActionRole.Arn
        Version: '2012-10-17'
      PolicyName: CodePipelineDefaultPolicy
      Roles:
        - !Ref CodePipelineRole
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location: !Ref CodePipelineArtifactsBucket
        Type: S3
      ExecutionMode: QUEUED
      Name: !Ref CodePipelineName
      PipelineType: V2
      RoleArn: !GetAtt CodePipelineRole.Arn
      Stages:
        - Name: Source
          Actions:
            - Name: CodeConnections
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: '1'
              Configuration:
                ConnectionArn: !Ref ConnectionArn
                FullRepositoryId: !Ref FullRepositoryId
                BranchName: !Ref BranchName
                DetectChanges: 'false'
              OutputArtifacts:
                - Name: SourceOutput
              RoleArn: !GetAtt CodeConnectionsActionRole.Arn
              RunOrder: 1
        - Name: MavenBuild
          BeforeEntry:
            Conditions:
              - Result: FAIL
                Rules:
                  - Name: MyDeploymentWindowRule
                    RuleTypeId:
                      Category: Rule
                      Owner: AWS
                      Provider: DeploymentWindow
                      Version: '1'
                    Configuration:
                      Cron: '* * * * * ? *'
                      TimeZone: 'PST'
          Actions:
            - Name: CI_Maven_Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName:
                  Fn::Join:
                    - '-'
                    - - SimpleScheduleMavenBuildProject
                      - Fn::Select:
                          - 4
                          - Fn::Split:
                              - '-'
                              - Fn::Select:
                                  - 2
                                  - Fn::Split:
                                      - /
                                      - Ref: AWS::StackId
              InputArtifacts:
                - Name: SourceOutput
              RoleArn: !GetAtt CodeBuildActionRole.Arn
              RunOrder: 1
    DependsOn:
      - CodePipelineDefaultPolicy
  CodeConnectionsActionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
        Version: '2012-10-17'
  CodeConnectionsActionDefaultPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: codestar-connections:UseConnection
            Effect: Allow
            Resource: !Ref ConnectionArn
          - Action:
              - s3:Abort*
              - s3:DeleteObject*
              - s3:GetBucket*
              - s3:GetObject*
              - s3:List*
              - s3:PutObject
              - s3:PutObjectLegalHold
              - s3:PutObjectRetention
              - s3:PutObjectTagging
              - s3:PutObjectVersionTagging
            Effect: Allow
            Resource:
              - !GetAtt CodePipelineArtifactsBucket.Arn
              - !Join
                - /
                - - !GetAtt CodePipelineArtifactsBucket.Arn
                  - '*'
          - Action:
              - s3:PutObjectAcl
              - s3:PutObjectVersionAcl
            Effect: Allow
            Resource: !Join
              - /
              - - !GetAtt CodePipelineArtifactsBucket.Arn
                - '*'
        Version: '2012-10-17'
      PolicyName: CodeConnectionsActionDefaultPolicy
      Roles:
        - !Ref CodeConnectionsActionRole
  CodeBuildActionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
        Version: '2012-10-17'
  CodeBuildActionDefaultPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - codebuild:BatchGetBuilds
              - codebuild:StartBuild
              - codebuild:StopBuild
            Effect: Allow
            Resource: !GetAtt CodeBuildProject.Arn
        Version: '2012-10-17'
      PolicyName: CodeBuildActionDefaultPolicy
      Roles:
        - !Ref CodeBuildActionRole